courses/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # home page
    path('', views.index, name="index"),
    
    # course - category - review
    path('courses/<int:course_id>/', views.course_detail, name='course_detail'),
    path('category/<int:category_id>/', views.category_courses, name='category_courses'),
    path('review/create', views.create_review, name="create-review"),
    # upload course
    path('upload/', views.upload_course, name='upload_course'),
    path('course/<int:pk>/update/', views.update_course, name='update_course'),
    path('course/<int:pk>/delete/', views.delete_course, name='delete_course'),

    # dashboard - change group permission
    path("dashboard", views.dashboard, name="dashboard"),
    path('become-instructor/', views.become_instructor, name='become_instructor'),
    
    # auth
    path('register', views.RegisterView.as_view(), name="register"),
    path('signout', views.signout, name="signout"),

    # shopping cart
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),

    # checkout    
    path('checkout', views.checkout, name="checkout"),
]

eLearning/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import datetime
from django.db.models import Avg


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name
    
class Course(models.Model):
    instructor = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.FloatField(default=0.0)
    image = models.ImageField(null=True, blank=True, default='noimage.jpg', upload_to="courses/")
    created_at = models.DateTimeField(auto_now_add=True)
    
    def get_reviews(self):
        if self.review_set.all() is not None:
            return self.review_set.all()
        return []

class Enrollment(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    courses = models.ManyToManyField(Course)
    total = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)


class Media(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    courses_video = models.FileField(upload_to='courses_video/')


class Review(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    stars = models.IntegerField(
        default=1, validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    description = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

courses/forms.py
from django import forms
from django.forms import ModelForm
from django.core.validators import MinValueValidator, MaxValueValidator
from .models import Review
from .models import Course
from .models import Media
from django.forms import formset_factory

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ["stars", "description"]
        # fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4, 'class': 'form-control'}),
            'stars': forms.NumberInput(attrs={'min': 1, 'max': 5, 'step': 1, 'class': 'form-control'}),
        }
        validators = [
            MinValueValidator(1),
            MaxValueValidator(5)
        ]

    def clean_stars(self):
        stars = self.cleaned_data['stars']
        if stars < 1 or stars > 5:
            raise forms.ValidationError("Stars must be between 1 and 5.")
        return stars
    
class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['category', 'name', 'description', 'price', 'image']
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'rows': 4, 'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }

class VideoForm(forms.ModelForm):
    class Meta:
        model = Media
        fields = ['name', 'courses_video']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'courses_video': forms.FileInput(attrs={'class': 'form-control'}),
        }

class CourseSearchForm(forms.Form):
    search_query = forms.CharField(label='Search Courses', max_length=100)

VideoFormSet = forms.inlineformset_factory(Course, Media, form=VideoForm, extra=1, can_delete=True)

courses/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.views import View
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Group, Permission
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CourseForm, VideoFormSet, CourseSearchForm, ReviewForm
from .models import *
from cart.cart import Cart

# home page
def index(request):
    courses_list = Course.objects.all().order_by("-id")
    categories = Category.objects.all()

    search_query = request.GET.get('q')
    if search_query:
        courses_list = courses_list.filter(name__icontains=search_query)
    
    page_num = request.GET.get("page", 1)

    paginator = Paginator(courses_list, 9)

    try:
        courses = paginator.page(page_num)
    except PageNotAnInteger:
        courses = paginator.page(1)
    except EmptyPage:
        courses = paginator.page(paginator.num_pages)


    search_form = CourseSearchForm()

    enrolled_courses = []
    if request.user.is_authenticated:
        enrolled_courses = Enrollment.objects.filter(student=request.user).values_list('courses', flat=True)


    context = {"courses": courses, "categories": categories, "search_form": search_form, "enrolled_courses": enrolled_courses}
    return render(request, "home.html", context)

# category page
def category_courses(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    courses_list = Course.objects.filter(category=category)
    categories = Category.objects.all()
    page_num = request.GET.get("page", 1)

    paginator = Paginator(courses_list, 9)

    try:
        courses = paginator.page(page_num)
    except PageNotAnInteger:
        courses = paginator.page(1)
    except EmptyPage:
        courses = paginator.page(paginator.num_pages)

    context = {"courses": courses, "categories": categories, 'category':category}
    return render(request, "category.html", context)

# course detail
# @login_required
def course_detail(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    videos = Media.objects.filter(course=course)
    is_enrolled = False
    is_student = False
    if request.user.groups.filter(name='student').exists():
        is_student = True
    if request.user.is_authenticated:
        if Enrollment.objects.filter(student=request.user, courses=course).exists():
            is_enrolled = True
            messages.info(request, "You are already enrolled in this course.")
    context = {"course": course, "review_form": ReviewForm, "is_enrolled": is_enrolled, "videos": videos, "is_student": is_student}
    return render(request, "course_detail.html", context)

# add review
@login_required
@user_passes_test(lambda u: u.groups.filter(name='instructor').exists())
def create_review(request):
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = Review(
                student=User.objects.filter(id=request.POST["student_id"]).first(),
                course=Course.objects.filter(id=request.POST["course_id"]).first(),
                stars=request.POST["stars"],
                description=request.POST["description"],
            )
            review.save()
            return redirect("course_detail", request.POST["course_id"])

    return redirect("course_detail", request.POST["course_id"])

# user dashboard
@login_required
def dashboard(request):
    user = request.user
    if user.groups.filter(name='student').exists():
        context = {"enrollments": Enrollment.objects.filter(student_id=request.user.id)}
    else:
        context = {"courses": Course.objects.filter(instructor_id=request.user.id)}
    return render(request, "dashboard.html", context)

# change group permission
@login_required
def become_instructor(request):
    user = request.user

    if user.groups.filter(name="instructor").exists():
        messages.info(request, "You are already a instructor.")
        return redirect("dashboard")

    if user.groups.filter(name="student").exists():
        user.groups.remove(Group.objects.filter(name="student").first())
        user.groups.add(Group.objects.filter(name="instructor").first())
        messages.success(request, "You have become a instructor.")

    return redirect("dashboard")

# auth
class RegisterView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect("index")

        form = UserCreationForm()

        context = {"form": form}

        return render(request, "registration/register.html", context)

    def post(self, request):
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=password)
            user.groups.add(Group.objects.filter(name="student").first())
            login(request, user)
            return redirect("index")
        return render(request, "home.html", {"form": form})


def signout(request):
    logout(request)
    return redirect("login")

#shopping cart 
@login_required
def cart_add(request, id):
    cart = Cart(request)
    course = Course.objects.get(id=id)
    cart.add(product=course)
    return redirect("index")


@login_required
def item_clear(request, id):
    cart = Cart(request)
    course = Course.objects.get(id=id)
    cart.remove(course)
    return redirect("index")

@login_required
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("cart_detail")


@login_required
def cart_detail(request):
    return render(request, 'cart/cart_detail.html')

# upload course
@login_required
@permission_required("courses.add_course")
def upload_course(request):
    if request.method == 'POST':
        course_form = CourseForm(request.POST, request.FILES)
        video_formset = VideoFormSet(request.POST, request.FILES)

        if course_form.is_valid() and video_formset.is_valid():
            course = course_form.save(commit=False)
            course.instructor = request.user
            course.save()
            videos = video_formset.save(commit=False)
            for video in videos:
                video.course = course
                video.save()
            return redirect('course_detail', course_id=course.id)
    else:
        course_form = CourseForm()
        video_formset = VideoFormSet()

    return render(request, 'upload_course.html', {
        'course_form': course_form,
        'video_formset': video_formset,
    })

# update course
@login_required
def update_course(request, pk):
    course = get_object_or_404(Course, pk=pk)
    if request.method == 'POST':
        course_form = CourseForm(request.POST, request.FILES, instance=course)
        video_formset = VideoFormSet(request.POST, request.FILES, instance=course)

        if course_form.is_valid() and video_formset.is_valid():
            course_form.save()
            video_formset.save()
            messages.success(request, "Course updated successfuly")
            return redirect('course_detail', course_id=course.pk)
    else:
        course_form = CourseForm(instance=course)
        video_formset = VideoFormSet(instance=course)
    
    return render(request, 'update_course.html', {
        'course_form': course_form,
        'video_formset': video_formset,
    })
# delete course
@login_required
def delete_course(request, pk):
    course = get_object_or_404(Course, pk=pk)
    course.delete()
    return redirect('dashboard')

# checkout
@login_required
def checkout(request):
    cart = request.session.get("cart", {}).items()

    total = 0
    for id, item in cart:
        total += float(item['price'])

    enrollment = Enrollment(student=request.user, total=total)
    enrollment.save()

    for id, item in cart:
        enrollment.courses.add(Course.objects.filter(name=item['name']).first())

    c = Cart(request)
    c.clear()

    return redirect('dashboard')

courses/templates/category.html
{% extends "layouts/app.html" %}
{% load course_filters %}

{% block title %}
{{ category.name }}
{% endblock %}

{% block content %}

<nav class="nav p-3 justify-content-center bg-primary">
    {% for category in categories %}
        <a class="nav-link text-white link-info" aria-current="page" href="{% url 'category_courses' category.id %}">{{ category.name }}</a>
    {% endfor %}
</nav>
<div class="container my-5">
  <h3 class="mb-5">{{ category.name }}</h3>
{% if courses %}
    <div class="row mb-2">
        {% for course in courses %}
        <div class="card col-md-3 border-0 rounded-0">
            <a href="{% url 'course_detail' course.id %}" class="h-100"><img src="{{ course.image.url }}"
                    class="card-img-top rounded-0" alt="..."></a>
            <div class="card-body p-0">
                <a href="{% url 'course_detail' course.id %}" class="link-dark" title="{{ course.name }}">
                    <h5 class="card-title text-truncate">{{ course.name }}</h5>
                </a>
                <p class="card-text m-1 text-capitalize">{{ course.instructor }}</p>
                <p class="d-flex align-items-center text-muted m-1 small">
                    <strong class="me-2 text-dark">{{ course.get_reviews|average_stars }}</strong>
                    {% if course.get_reviews.count > 0 %}
                        {% with course.get_reviews|average_stars as average_stars %}
                            {% for i in "x"|rjust:average_stars %}
                                <i class="bx bxs-star text-warning"></i>
                            {% endfor %}
                        {% endwith %}
                    {% endif %}
                    <span>({{ course.get_reviews.count }})</span>
                </p>
                <p class="m-1"><strong>{{ course.price }}$</strong></p>
                <a href="{% url 'cart_add' course.id %}" class="btn btn-primary rounded-0">Add to cart</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="alert alert-info" role="alert">
        0 Courses
    </div>
    {% endif %}

    <nav aria-label="Page navigation example">
        <ul class="pagination">
          {% if courses.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ courses.previous_page_number }}">Previous</a></li>
          {% else %}
            <li class="page-item disabled"><span class="page-link">Previous</span></li>
          {% endif %}
      
          {% for i in courses.paginator.page_range %}
            {% if courses.number == i %}
              <li class="page-item active"><span class="page-link">{{ i }}</span></li>
            {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}
      
          {% if courses.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ courses.next_page_number }}">Next</a></li>
          {% else %}
            <li class="page-item disabled"><span class="page-link">Next</span></li>
          {% endif %}
        </ul>
      </nav>
</div>
{% endblock %}

courses/templates/course_detail.html
{% extends "layouts/app.html" %}
{% block title %}
{{ course.name }}
{% endblock %}

{% block content %}
{% if messages %}
<div>
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>
{% endif %}
<div class="container my-5">
    <div class="row">
        <div class="col-12 col-md-4">
            <img src="{{ course.image.url }}" class="img-thumbnail w-100" alt="{{ course.name }}" />
        </div>
        <div class="col-12 col-md-8">
            <div class="card border-0">
                <div class="card-body">
                    <h3 class="card-title">{{ course.name }}</h3>
                    <p class="card-text">{{ course.description }}</p>
                    <p class="small">Created by {{ course.instructor }}</p>
                    <p class="small">Created at {{ course.created_at }}</p>
                    {% if not is_enrolled %}
                    <a href="{% url 'cart_add' course.id %}" class="btn btn-outline-primary rounded-0">Add to Cart</a>
                    {% else %}
                    <a href="#" class="btn btn-outline-danger rounded-0 disabled">You are already enrolled in this course.</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-12">
            {% for video in videos %}
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">{{ video.name }}</h5>
                    <video width="100%" controls>
                        <source src="{{ video.courses_video.url }}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% if course.get_reviews|length > 0 %}
        {% for review in course.get_reviews %}
            <div class="card my-3">
                <div class="card-body">
                    {% for i in ""|ljust:review.stars %}
                    <i class="bx bxs-star text-warning"></i>
                    {% endfor %}
                    <p class="mt-1">
                        <i>{{ review.description }}</i>
                        <br />
                        - {{ review.student }}
                    </p>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    {% if is_student %}
    <div class="card col-md-3 col-12">
        <div class="card-body">
            <h3>Review</h3>
            {{ review_form.errors }}
            <form action="{% url 'create-review' %}" method="POST">
                {% csrf_token %}
                {{ review_form.as_p }}
                <input type="hidden" name="student_id" value="{{ request.user.id }}">
                <input type="hidden" name="course_id" value="{{ course.id }}">
                <button type="submit" class="btn btn-sm rounded-0 btn-outline-primary">Submit</button>
            </form>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

courses/templates/dashboard.html
{% extends "layouts/app.html" %}

{% block title %}
Dashboard
{% endblock %}

{% block content %}
{% if messages %}
<div>
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>
{% endif %}
<div class="container my-5">
    {% if perms.courses.add_course %}
    <a href="{% url 'upload_course' %}" class="btn btn-primary rounded-0">Add new Course</a>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Image</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Price</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for course in courses %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td class="w-25"><img class="img-thumbnail w-25" src="{{ course.image.url }}" alt="{{ course.name }}">
                </td>
                <td>{{course.name}}</td>
                <td>{{course.description}}</td>
                <td>{{course.price}}</td>
                <td>
                    <div class="d-flex align-items-center">
                        <a href="{% url 'update_course' course.id %}" class="btn btn-transparent"><i class="bx bx-pencil text-warning h5"></i></a>
                    <form method="post" action="{% url 'delete_course' course.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-transparent"><i class="bx bx-trash text-danger h5"></i></button>
                    </form>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% else %}
    {% if enrollments %}
    <table class="table">
        <h3>Enrollments</h3>
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Image</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
            {% for enrollment in enrollments %}
            {% for course in enrollment.courses.all %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td class="w-25"><img class="img-thumbnail w-25" src="{{ course.image.url }}" alt="{{ course.name }}">
                </td>
                <td>{{course.name}}</td>
                <td>{{course.description}}</td>
                <td>{{course.price}}</td>
            </tr>
            {% endfor %}
            <tr class="text-end">
                <td colspan="4"><strong>Total:</strong></td>
                <td colspan="4">{{ enrollment.total|floatformat:2 }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
        {% else %}
        <div class="alert alert-info" role="alert">
            0 Enrollments
        </div>
    {% endif %}
    {% endif %}

</div>
{% endblock %}

courses/templates/home.html
{% extends "layouts/app.html" %}
{% load mathfilters %}
{% load course_filters %}

{% block title %}
Home
{% endblock %}

{% block content %}

<nav class="nav p-3 justify-content-center bg-primary">
    {% for category in categories %}
        <a class="nav-link text-white link-info" aria-current="page" href="{% url 'category_courses' category.id %}">{{ category.name }}</a>
    {% endfor %}
</nav>
<div class="container my-5">
{% if courses %}
    <div class="row mb-2">
        {% for course in courses %}
        <div class="card col-md-3 border-0 rounded-0">
            <a href="{% url 'course_detail' course.id %}" class="h-100"><img src="{{ course.image.url }}"
                    class="card-img-top rounded-0" alt="..."></a>
            <div class="card-body p-0">
                <a href="{% url 'course_detail' course.id %}" class="link-dark" title="{{ course.name }}">
                    <h5 class="card-title text-truncate">{{ course.name }}</h5>
                </a>
                <p class="card-text m-1 text-capitalize">{{ course.instructor }}</p>
                <p class="d-flex align-items-center text-muted m-1 small">
                    <strong class="me-2 text-dark">{{ course.get_reviews|average_stars }}</strong>
                    {% if course.get_reviews.count > 0 %}
                        {% with course.get_reviews|average_stars as average_stars %}
                            {% for i in "x"|rjust:average_stars %}
                                <i class="bx bxs-star text-warning"></i>
                            {% endfor %}
                        {% endwith %}
                    {% endif %}
                    <span>({{ course.get_reviews.count }})</span>
                </p>
                <p class="m-1"><strong>{{ course.price }}$</strong></p>
                {% if course.id not in enrolled_courses %}
                <a href="{% url 'cart_add' course.id %}" class="btn btn-primary rounded-0">Add to cart</a>
                {% else %}
                <a href="#" class="btn btn-outline-danger rounded-0 disabled">You are already enrolled in this course.</a>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="alert alert-info" role="alert">
        0 Courses
    </div>
    {% endif %}

    <nav aria-label="Page navigation example">
        <ul class="pagination">
          {% if courses.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ courses.previous_page_number }}">Previous</a></li>
          {% else %}
            <li class="page-item disabled"><span class="page-link">Previous</span></li>
          {% endif %}
      
          {% for i in courses.paginator.page_range %}
            {% if courses.number == i %}
              <li class="page-item active"><span class="page-link">{{ i }}</span></li>
            {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}
      
          {% if courses.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ courses.next_page_number }}">Next</a></li>
          {% else %}
            <li class="page-item disabled"><span class="page-link">Next</span></li>
          {% endif %}
        </ul>
      </nav>
</div>
{% endblock %}

courses/templates/update_course.html
{% extends "layouts/app.html" %}

{% block title %}
Update Course
{% endblock %}

{% block content %}
{% if messages %}
<div>
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>
{% endif %}
<div class="container my-5">
    {% if perms.courses.change_course %}
    <h1>Update Course</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ course_form.as_p }}
        </div>
        <h2>Videos</h2>
        {{ video_formset.management_form }}
        {% for form in video_formset %}
            <div class="form-group">
                {{ form.id }}
                {{ form.name.label_tag }} {{ form.name }}
                {{ form.courses_video.label_tag }} {{ form.courses_video }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
    {% endif %}
</div>
{% endblock %}

courses/templates/upload_course.html
{% extends "layouts/app.html" %}

{% block title %}
Course Upload
{% endblock %}

{% block content %}
{% if messages %}
<div>
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>
{% endif %}
<div class="container my-5">
    {% if course_form.errors %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        {{ course_form.errors }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% if perms.courses.add_course %}
    <h1>Upload Course</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{ course_form.non_field_errors }}
                {{ course_form.as_p }}
                {% for field in course_form %}
                    {% if field.errors %}
                        <div class="alert alert-danger">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="form-group">
                {{ video_formset.management_form }}
                {{ video_formset.non_field_errors }}
                {% for form in video_formset %}
                    {% if not form.empty_form %}
                        <div class="form-group mb-3">
                            {{ form.id }}
                            {{ form.name.label_tag }} {{ form.name }}
                            {% if form.name.errors %}
                                <div class="alert alert-danger">
                                    {{ form.name.errors }}
                                </div>
                            {% endif %}
                            {{ form.courses_video.label_tag }} {{ form.courses_video }}
                            {% if form.courses_video.errors %}
                                <div class="alert alert-danger">
                                    {{ form.courses_video.errors }}
                                </div>
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <button type="submit" class="btn btn-primary">Upload</button>
        </form>
    {% endif %}
</div>
{% endblock %}